name: PROD reactapplication CICD

on:
  push:
    branch:
          - feature --disable
jobs:
  build:

    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v4
    - name: reactjs application
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - run: |
          ls
          npm install  
    - run: npm install -g create-react-app
    - run: npm ci
    - run: npm install gh-pages --save-devgit
    - run: npm run build
    - name: Install AWS CLI
      run: |
           sudo apt-get install awscli
    - name: Upload to S3
      run: aws s3 cp build/ s3://react44newapp/ --recursive
      env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_REGION: us-east-1